name: "Actions Workflow 🚀"

## Description: Search the code for UNDEFINED_VERSION and replaces it with the deployed version.

on:
  # Triggers the workflow when a PR is closed (merged, or just closed)
  pull_request:
    types: [ "closed" ]
    branches: [ "run-tests" ]

env:
   DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
   FORCE_COLOR: true
   TERM: xterm-256color

jobs:
  build:

    name: Actions Workflow ⚙️
    container:
      image: quay.io/pantheon-public/build-tools-ci:8.x-php8.2
      options: --user root
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
  
      - name: Setup the environment
        run: |
          TMP_COMPOSER_VERSION='2.8.6'
          echo "COMPOSER_VERSION=${TMP_COMPOSER_VERSION}"
          echo "COMPOSER_VERSION=${TMP_COMPOSER_VERSION}" >> $GITHUB_ENV
          
          DEPLOYMENT_DIR="`echo $GITHUB_REPOSITORY | awk -F '/' '{printf $2}'`"
          echo "DEPLOYMENT_DIR=${DEPLOYMENT_DIR}"
          echo "DEPLOYMENT_DIR=${DEPLOYMENT_DIR}" >> $GITHUB_ENV

      - name: Populate composer_auth
        id: set_composer_auth
        run: |
          cat > /tmp/composer_auth <<EOF
            '{
                "github-oauth": {
                    "github.com": "${{ secrets.GITHUB_TOKEN }}"
                }
            }'
          EOF

          TMP_COMPOSER_AUTH="$(echo `cat /tmp/composer_auth | sed s/\'//g`)"
          echo "COMPOSER_AUTH<<EOF" >> $GITHUB_ENV
          echo "$TMP_COMPOSER_AUTH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: CheckOut Source Code
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: main
          path: ${{ env.DEPLOYMENT_DIR }}
          fetch-depth: 0
          persist-credentials: true
          set-safe-directory: true
          submodules: 'recursive'
          clean: true

      - name: Composer Automatic install
        id: composer_automatic_install
        run: |
          echo "Current version is: `composer --version`"

          #DOC : https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
          echo "Let's do an automatic install... "
          wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet

          echo ''
          echo "New version is: `composer --version`"
          echo ''
          composer -n self-update ${{ env.COMPOSER_VERSION }} --ansi
          echo ''
          echo ''
          composer diagnose --ansi || true

          echo "➕`php --version`" >> $GITHUB_STEP_SUMMARY
          echo "➕`composer --version`" >> $GITHUB_STEP_SUMMARY
          echo "-------" >> $GITHUB_STEP_SUMMARY

      - name: Cache composer global 💾
        id: cache-composer-global
        uses: actions/cache@v3
        env:
          cache_name: cache-composer-global-${{ hashFiles('composer.lock') }}
          hash: ${{ hashFiles('composer.lock') }}
        with:
          path: ~/.composer
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ env.hash }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache_name }}
          
      # @TODO check necessary scripts + add to summary
      - name: Composer install
        working-directory: ${{ env.DEPLOYMENT_DIR }}
        id: composer_install
        run: composer install --ansi --verbose
          
      - name: Runnning Test(s)
        working-directory: ${{ env.DEPLOYMENT_DIR }}
        run: |
         ./vendor/bin/phpunit --colors tests/ 2>&1 | tee output.log
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -n 1000 output.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          

          
