name: "Actions Workflow 🚀"

## Description: Search the code for UNDEFINED_VERSION and replaces it with the deployed version.
## - XXXXXX

on:
  # Triggers the workflow when a PR is closed (merged, or just closed)
  pull_request:
    types: [ "closed" ]
    branches: [ "run-tests" ]

env:
   DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
   FORCE_COLOR: 'true'
   TERM: 'xterm-color'

jobs:
  build:
    name: Actions Workflow
    runs-on: ubuntu-latest
    steps:
  
      - name: Setup the environment
        run: |
          DEPLOYMENT_DIR="`echo $GITHUB_REPOSITORY | awk -F '/' '{printf $2}'`"
          echo "DEPLOYMENT_DIR=${DEPLOYMENT_DIR}"
          echo "DEPLOYMENT_DIR=${DEPLOYMENT_DIR}" >> $GITHUB_ENV

      - name: Populate composer_auth
        id: set_composer_auth
        run: |
          cat > /tmp/composer_auth <<EOF
            '{
                "github-oauth": {
                    "github.com": "${{ secrets.GITHUB_TOKEN }}"
                }
            }'
          EOF

          TMP_COMPOSER_AUTH="$(echo `cat /tmp/composer_auth | sed s/\'//g`)"
          echo "COMPOSER_AUTH<<EOF" >> $GITHUB_ENV
          echo "$TMP_COMPOSER_AUTH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: CheckOut Source Code
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: main
          path: ${{ env.DEPLOYMENT_DIR }}
          fetch-depth: 0
          persist-credentials: true
          set-safe-directory: true
          submodules: 'recursive'
          clean: true
      
      - name: Composer diagnose
        working-directory: ${{ env.DEPLOYMENT_DIR }}
        id: composer_diagnose
        run: composer diagnose || true

      # @TODO check necessary scripts + add to summary
      - name: Composer install
        working-directory: ${{ env.DEPLOYMENT_DIR }}
        id: composer_install
        run: composer install --verbose
          
      - name: Runnning Test(s)
        working-directory: ${{ env.DEPLOYMENT_DIR }}
        run: |
          ./vendor/bin/phpunit tests/

          
