name: "gcms_plugin_version_updater_workflow 🚀"

## Description: THIS TRIGGERS ON ALL PULL REQUEST CLOSE / MERGE
## - XXXXXX

on:
  # Triggers the workflow when a PR is closed (merged, or just closed)
  pull_request:
    types: [ "closed" ]
    branches: [ "master","main" ]

jobs:
  build:
    name: RedisTimeSeries
    runs-on: ubuntu-latest
    steps:
      - id: KeyDB
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          owner: JohnSully
          repo: KeyDB
          excludes: prerelease, draft

      - uses: actions/checkout@v3
      
      - name: Deleting any orphaned Multidev environments
        id: showing
        shell: bash
        run: |
          echo "VERSION :  >>> ${{ steps.keydb.outputs.release }} <<<<<"
          echo " tags: latest, ${{ steps.keydb.outputs.release }}_${{ steps.timeseries.outputs.release }}"
