name: "gcms_plugin_version_updater_workflow 🚀"

## Description: THIS TRIGGERS ON ALL PULL REQUEST CLOSE / MERGE
## - XXXXXX

on:
  # Triggers the workflow when a PR is closed (merged, or just closed)
  pull_request:
    types: [ "closed" ]
    branches: [ "master","main" ]

defaults:
  run:
    shell: bash


jobs:


#################################
# SETUP
#################################

  Build:
    name: Build ⚙️
    container:
      image: quay.io/pantheon-public/build-tools-ci:8.x-php${{ inputs.PHP_VERSION }}
      options: --user root
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: JohnSully
          repo: KeyDB
          excludes: prerelease, draft
      - id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: RedisTimeSeries/RedisTimeSeries