name: "Update version 🚀"

description: Search the code for __GCFO_UNDEFINED_VERSION__ and replaces it with the last release version.

on:
  push:
    branches: [ wip ]
  # pull_request:
  #   branches: [ main, master ]

env:
    DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
    FORCE_COLOR: true
    TERM: xterm-256color
    PHP_VERSION: '8.4'

jobs:
  build:
    name: Update version
    runs-on: ubuntu-latest
  
    steps:
  
      - id: KeyDB
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          owner: JohnSully
          repo: KeyDB
          excludes: prerelease, draft

      - name: Setup the environment
        run: |
          LAST_VERSION="`echo ${{ steps.keydb.outputs.release }}`"
          echo "LAST_VERSION=${LAST_VERSION}"
          echo "LAST_VERSION=${LAST_VERSION}" >> $GITHUB_ENV

          # Please use __GCFO_UNDEFINED_VERSION__ in your code
          TMP_UNDEFINED_VERSION="__GCFO_UNDEFINED_VERSION__"
          echo "UNDEFINED_VERSION=${TMP_UNDEFINED_VERSION}"
          echo "UNDEFINED_VERSION=${TMP_UNDEFINED_VERSION}" >> $GITHUB_ENV

      - name: CheckOut Source Code
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: wip
          fetch-depth: 0
          persist-credentials: true
          set-safe-directory: true
          submodules: 'recursive'
          clean: true
          
      - name: 🔍 Listing the files to be modified
        id: search_code
        run: |
          SEARCH_CMD="grep -rni --exclude-dir={.git,vendor,.github} \"${{ env.UNDEFINED_VERSION }}\" ."

          echo "$SEARCH_CMD"
          
          # Continue only if we have something to modify
          if [[ -n "$SEARCH_CMD" ]]; then 
            echo "modify_source=true" >> $GITHUB_OUTPUT
          fi
          
          
      - name: ✨ Running the modification
        if: ${{ steps.search_code.outputs.modify_source == true }}
        run: |
          for file in `grep -rl --exclude-dir={.git,vendor,.github} "${{ env.UNDEFINED_VERSION }}" .`; do
            sed -i "s/${{ env.UNDEFINED_VERSION }}/${{ env.LAST_VERSION }}/g" $file
          done

      - name: Commit and push changes
        if: ${{ steps.search_code.outputs.modify_source == true }}
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "(pipeline) Update version:${{ env.LAST_VERSION }}"
